# vim:ft=kitty

## name:     Ocular Kitty Manzanilla
## author:   Rafael Farias (Ocular)
## license:  MIT
## blurb:    Port Ocular — misma estructura de campos que catppuccin/kitty.



# The basic colors
foreground              #3f372d
background              #f5efe7
selection_foreground    #f5efe7
selection_background    #8f4536

# Cursor colors
cursor                  #8f4536
cursor_text_color       #f5efe7

# Scrollbar colors
scrollbar_handle_color  #817a73
scrollbar_track_color   #d9d3c9

# URL color when hovering with mouse
url_color               #8f4536

# Kitty window border colors
active_border_color     #4655a5
inactive_border_color   #a19c94
bell_border_color       #835000

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color background

# Tab bar colors
active_tab_foreground   #e6e0d7
active_tab_background   #684c9e
inactive_tab_foreground #3f372d
inactive_tab_background #eee8df
tab_bar_background      #e6e0d7

# Colors for marks (marked text in the terminal)
mark1_foreground #f5efe7
mark1_background #4655a5
mark2_foreground #f5efe7
mark2_background #684c9e
mark3_foreground #f5efe7
mark3_background #006474

# The 16 terminal colors

# black
color0 #d9d3c9
color8 #cec9bf

# red
color1 #9b393f
color9 #892830

# green
color2  #276819
color10 #155903

# yellow
color3  #835000
color11 #6e4300

# blue
color4  #3259a4
color12 #244a93

# magenta
color5  #8d3d78
color13 #7c2d68

# cyan
color6  #00656a
color14 #005559

# white
color7  #544c43
color15 #443d34
