# vim:ft=kitty

## name:     Ocular Kitty Rooibos Deutan
## author:   Rafael Farias (Ocular)
## license:  MIT
## blurb:    Port Ocular — misma estructura de campos que catppuccin/kitty.



# The basic colors
foreground              #dfd9cc
background              #1e1a15
selection_foreground    #1e1a15
selection_background    #efc7bf

# Cursor colors
cursor                  #efc7bf
cursor_text_color       #1e1a15

# Scrollbar colors
scrollbar_handle_color  #b4afa8
scrollbar_track_color   #38322b

# URL color when hovering with mouse
url_color               #efc7bf

# Kitty window border colors
active_border_color     #d0cbff
inactive_border_color   #98938d
bell_border_color       #eecd7c

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color background

# Tab bar colors
active_tab_foreground   #15110d
active_tab_background   #e4b1f4
inactive_tab_foreground #dfd9cc
inactive_tab_background #191511
tab_bar_background      #15110d

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1a15
mark1_background #d0cbff
mark2_foreground #1e1a15
mark2_background #e4b1f4
mark3_foreground #1e1a15
mark3_background #7bc6f6

# The 16 terminal colors

# black
color0 #38322b
color8 #464038

# red
color1 #ffb2b1
color9 #ffc0bf

# green
color2  #a5ce92
color10 #afd89c

# yellow
color3  #eecd7c
color11 #f8d685

# blue
color4  #a5c9ff
color12 #b5d3ff

# magenta
color5  #fab1d9
color13 #ffbee1

# cyan
color6  #6ed8d0
color14 #79e3da

# white
color7  #d1cbc0
color15 #dbd5ca
