# vim:ft=kitty

## name:     Ocular Kitty Manzanilla
## author:   Rafael Farias (Ocular)
## license:  MIT
## blurb:    Port Ocular — misma estructura de campos que catppuccin/kitty.



# The basic colors
foreground              #3f372d
background              #f5efe7
selection_foreground    #f5efe7
selection_background    #77534e

# Cursor colors
cursor                  #77534e
cursor_text_color       #f5efe7

# Scrollbar colors
scrollbar_handle_color  #817a73
scrollbar_track_color   #d9d3c9

# URL color when hovering with mouse
url_color               #77534e

# Kitty window border colors
active_border_color     #5d5391
inactive_border_color   #a19c94
bell_border_color       #725800

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color background

# Tab bar colors
active_tab_foreground   #e6e0d7
active_tab_background   #744991
inactive_tab_foreground #3f372d
inactive_tab_background #eee8df
tab_bar_background      #e6e0d7

# Colors for marks (marked text in the terminal)
mark1_foreground #f5efe7
mark1_background #5d5391
mark2_foreground #f5efe7
mark2_background #744991
mark3_foreground #f5efe7
mark3_background #006090

# The 16 terminal colors

# black
color0 #d9d3c9
color8 #cec9bf

# red
color1 #9a3b38
color9 #882a29

# green
color2  #326726
color10 #225815

# yellow
color3  #725800
color11 #604a00

# blue
color4  #3458a3
color12 #264992

# magenta
color5  #8c406e
color13 #7b305e

# cyan
color6  #00665e
color14 #00554f

# white
color7  #544c43
color15 #443d34
