# vim:ft=kitty

## name:     Ocular Kitty Manzanilla Deutan
## author:   Rafael Farias (Ocular)
## license:  MIT
## blurb:    Port Ocular — misma estructura de campos que catppuccin/kitty.



# The basic colors
foreground              #3f372d
background              #f5efe7
selection_foreground    #f5efe7
selection_background    #69433c

# Cursor colors
cursor                  #69433c
cursor_text_color       #f5efe7

# Scrollbar colors
scrollbar_handle_color  #817a73
scrollbar_track_color   #d9d3c9

# URL color when hovering with mouse
url_color               #69433c

# Kitty window border colors
active_border_color     #4f4480
inactive_border_color   #a19c94
bell_border_color       #614a00

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color background

# Tab bar colors
active_tab_foreground   #e6e0d7
active_tab_background   #824992
inactive_tab_foreground #3f372d
inactive_tab_background #eee8df
tab_bar_background      #e6e0d7

# Colors for marks (marked text in the terminal)
mark1_foreground #f5efe7
mark1_background #4f4480
mark2_foreground #f5efe7
mark2_background #824992
mark3_foreground #f5efe7
mark3_background #006d9d

# The 16 terminal colors

# black
color0 #d9d3c9
color8 #cec9bf

# red
color1 #983c41
color9 #862b32

# green
color2  #3f6b26
color10 #305c15

# yellow
color3  #614a00
color11 #4e3b00

# blue
color4  #2c5aa3
color12 #1d4b92

# magenta
color5  #8c406e
color13 #7b305e

# cyan
color6  #006561
color14 #005551

# white
color7  #544c43
color15 #443d34
